export const Colors = {
  light: {
    primary: '#003EC7',
    primaryDark: '#002B8A',
    primaryContainer: '#0052FF',
    accent: '#00C6E0',
    background: '#F5F7FF',
    surface: '#FFFFFF',
    surfaceVariant: '#EEF2FF',
    surfaceContainer: '#E3EAFF',
    foreground: '#0A0A14',
    foregroundSecondary: '#434760',
    muted: '#8A8FA8',
    mutedForeground: '#6B7080',
    border: '#DDE3F0',
    borderLight: '#EEF2FF',
    error: '#BA1A1A',
    errorContainer: '#FFDAD6',
    success: '#006875',
    successContainer: '#9CF0FF',
    warning: '#B86A00',
    warningContainer: '#FFDCC0',
    card: '#FFFFFF',
    cardBorder: '#E8EDFF',
    tabBar: '#FFFFFF',
    tabBarBorder: '#EEF2FF',
    tabInactive: '#9BA3C0',
    radius: 12,
    radiusLg: 20,
    radiusFull: 999,
  },
};

export type ColorScheme = typeof Colors.light;
